
services:
  db:
    image: postgres:15
    container_name: kyc_postgres
    restart: always
    environment:
      POSTGRES_USER: kyc_user
      POSTGRES_PASSWORD: kyc_pass
      POSTGRES_DB: kyc_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: kyc_backend
    restart: always
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

volumes:
  postgres_data: